// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFGwrlfFaAMf5POZaYMBKtcwlsrnmTACI',
    appId: '1:123049725452:web:a31d5aa5c2a656cb69e829',
    messagingSenderId: '123049725452',
    projectId: 'fir-test-e3f25',
    authDomain: 'fir-test-e3f25.firebaseapp.com',
    storageBucket: 'fir-test-e3f25.appspot.com',
    measurementId: 'G-1B2HDL2QTZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBvTvHAKGV7BMSGVCQccRTQ7wq13KBV7as',
    appId: '1:123049725452:android:e66e5ee5373400a369e829',
    messagingSenderId: '123049725452',
    projectId: 'fir-test-e3f25',
    storageBucket: 'fir-test-e3f25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEEj7ukM8AukLGS9HqLxFB7_7dfCx2YbU',
    appId: '1:123049725452:ios:59d54512aa0d0b1369e829',
    messagingSenderId: '123049725452',
    projectId: 'fir-test-e3f25',
    storageBucket: 'fir-test-e3f25.appspot.com',
    iosClientId: '123049725452-9tl0s1r77580hfg7ds76rokq4n2695nh.apps.googleusercontent.com',
    iosBundleId: 'com.example.adListingFullApp',
  );
}
